# Generated by Django 4.2.30 on 2026-08-28 20:48

from django.db import migrations, models
import infraestructura.models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoservidor',
            name='direccion_ip',
            field=models.GenericIPAddressField(validators=[infraestructura.models.validar_ip_corporativa], verbose_name='Dirección IP'),
        ),
    ]
