# Generated by Django 4.2.30 on 2026-09-07 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0003_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='infraestructura.nodoservidor'),
        ),
        migrations.CreateModel(
            name='IncidenciaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción del Fallo')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Incidencia Resuelta?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='infraestructura.nodoservidor')),
            ],
            options={
                'verbose_name': 'Incidencia de Servidor',
                'verbose_name_plural': 'Incidencias de Servidores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
